name: $(Build.DefinitionName)-$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

variables:
  VERSION_COUNTER: $[counter('versioncounter', 100)]

trigger:
  branches:
    include:
    - feature/*
    exclude:
    - master
    - releases/*
    - hotfix/*

jobs:
- job: TestAndAnalyse
  pool:
    vmImage: 'macOS 10.13'
  steps:
  - template: azure-testandanalyse.yml
