# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

pool:
  vmImage: 'macOS 10.13'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    tasks: 'cleanAndInit'

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    tasks: 'assembleAppForCI'

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'runUnitTests'

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    tasks: 'jacocoMergedTestReport'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'jaCoCo'
    jacocoMergedTestReport: '$(System.DefaultWorkingDirectory)/app/**/jacocoMergedTestReport.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/app/build/reports/jacoco/jacocoMergedTestReport/html'
    additionalCodeCoverageFiles: 'build/jacoco/*.exec'

- task: Gradle@2
  env:
    ANDROID_SONAR_LOGIN: $(ANDROID_SONAR_LOGIN)
    AZURE_BRANCH: $(Build.SourceBranch)
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    tasks: 'sonarqube'

#- task: Gradle@2
#  inputs:
#    workingDirectory: ''
#    gradleWrapperFile: 'gradlew'
#    gradleOptions: '-Xmx3072m'
#    publishJUnitResults: false
#    tasks: 'configureMappingArtifacts configureApkArtifacts'

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    contents: 'app/build/reports/**/*.*'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
    artifactType: 'container'